version: '3'

services:
  mysql:
    image: mysql:8
    command: --mysql-native-password=ON
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: golang
    ports:
      - '3306:3306'
    volumes:
      - './sql/:/docker-entrypoint-initdb.d/'
