version: '3'

services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: golang
    ports:
      - '3306:3306'
    volumes:
      - './sql/:/docker-entrypoint-initdb.d/'
